### ISSUE TITLE
Crashes immediatly when trying to run

### ISSUE THREAD

**Issue by ghost** [Tronic/elonet-dl#1]
Trying to run it on Windows 10 x64 with Python 3.8 and I keep getting this error 

`Traceback (most recent call last):
  File "E:\DVD\elonet-dl.py", line 7, in <module>
    from bs4 import BeautifulSoup as bs
  File "C:\Users\myste\AppData\Local\Programs\Python\Python38-32\lib\site-packages\bs4\__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "C:\Users\myste\AppData\Local\Programs\Python\Python38-32\lib\site-packages\bs4\builder\__init__.py", line 314, in <module>
    from . import _html5lib
  File "C:\Users\myste\AppData\Local\Programs\Python\Python38-32\lib\site-packages\bs4\builder\_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'`

**Comment by Tronic** [comment]
This seems to be a problem with bs4/html5lib. Perhaps you have incompatible versions of them installed? Try reinstalling/upgrading with `pip`?

Or you could instead try with `youtube-dl` as it can download some or maybe even all Elonet videos now.

**Comment by ghost** [comment]
Latest version of youtube-dl doesn't work for it which is why I tried your script.
I'm guessing there was some issue with bs4 or html5lib because it started to work after reinstalling them. Thank you for your help
